// Generated by CoffeeScript 1.6.3
"use strict";
angular.module('workify').controller('BlockerCtrl', function($scope, $timeout) {
  var timefunc, timeout;
  $scope.remaining = 30;
  $scope.done = false;
  timeout = $timeout(timefunc = function() {
    if ($scope.remaining === 1) {
      return $scope.done = true;
    } else {
      $scope.remaining--;
      return $timeout(timefunc, 1000);
    }
  }, 1000);
  $scope.unblock = function() {
    return chrome.tabs.getCurrent(function(tab) {
      return chrome.runtime.sendMessage({
        method: 'unblock',
        args: [tab]
      });
    });
  };
  return window.unblock = $scope.unblock;
});
