// Generated by CoffeeScript 1.6.3
(function() {
  "use strict";
  angular.module('workify').controller('TodoCtrl', function($scope, Todos) {
    chrome.runtime.onMessage.addListener(function(msg) {
      if (msg === "updateList") {
        return $scope.$apply(function() {
          return Todos.get().then(function(todolist) {
            return $scope.todos = todolist;
          });
        });
      }
    });
    $scope.todos = Todos.get();
    $scope.update = function() {
      return Todos.update();
    };
    $scope.addTodo = function(title, energy) {
      return Todos.add(title, energy);
    };
    $scope.removeTodo = function(id) {
      return Todos.remove(id);
    };
  });

}).call(this);
