// Generated by CoffeeScript 1.6.3
angular.module('workify').controller('BlockerCtrl', function($scope, $timeout) {
  var countdown;
  $scope.remaining = 30;
  countdown = window.setInterval(function() {
    $scope.$apply(function() {
      return $scope.remaining--;
    });
    if ($scope.remaining === 0) {
      $scope.$emit('timeout');
      return window.clearInterval(countdown);
    }
  }, 1000);
  return $scope.$on('timeout', function() {
    return console.log('timer done. This would return to the original page if I\'d written that bit yet');
  });
});
