// Generated by CoffeeScript 1.6.3
angular.module('workify').controller('BlockCtrl', function($scope) {
  $scope.blocked = false;
  $scope.toggle = function() {
    return $scope.blocked = !$scope.blocked;
  };
});
