// Generated by CoffeeScript 1.6.3
"use strict";
angular.module('workify').controller('BlockCtrl', function($scope) {
  var Tab, url;
  Tab = null;
  url = null;
  chrome.runtime.getBackgroundPage(function(bg) {
    Tab = bg.Tab;
    return chrome.tabs.query({
      active: true,
      windowType: 'normal'
    }, function(tabs) {
      var tab;
      tab = tabs[0];
      url = tab.url;
      return Tab.inBlocklist(tab.url, function() {
        return $scope.$apply(function() {
          return $scope.blocked = true;
        });
      });
    });
  });
  $scope.blocked = false;
  $scope.toggle = function() {
    if (!$scope.blocked) {
      Tab.addToBlocklist(url);
    } else {
      Tab.removeFromBlocklist(url);
    }
    return $scope.blocked = !$scope.blocked;
  };
});
