// Generated by CoffeeScript 1.6.3
(function() {
  angular.module('workify').directive('enterKey', function() {
    return function(scope, elem, attrs) {
      return elem.bind('keydown', function(e) {
        if (e.keyCode === 13) {
          return scope.$apply(attrs.enterKey);
        }
      });
    };
  });

  angular.module('workify').directive('todoList', function($timeout) {
    return {
      restrict: 'E',
      replace: true,
      transclude: true,
      templateUrl: 'todo-list.html',
      scope: {
        todoList: '=todos',
        title: '@',
        emptyMessage: '@',
        energy: '@',
        removeFunc: '&remove',
        addFunc: '&add',
        updateFunc: '&update'
      },
      link: function(scope, elem, attrs) {
        var form, _i, _len, _ref;
        console.log(scope.todoList);
        if (scope.energy !== "") {
          scope.todos = scope.todoList[scope.energy];
        } else {
          scope.$watch('todoList', function() {
            return scope.todos = scope.todoList.high.concat(scope.todoList.low);
          }, true);
        }
        if (scope.emptyMessage === "") {
          scope.emptyMessage = "You have no tasks in this list.";
        }
        if (attrs.customForm != null) {
          _ref = elem.find('form');
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            form = _ref[_i];
            if (form.className.match(/default-form/)) {
              form.remove();
              break;
            }
          }
        }
        return scope.getEnergy = function(id) {
          if (scope.energy !== "") {
            return scope.energy;
          } else {

          }
        };
      }
    };
  });

}).call(this);
