// Generated by CoffeeScript 1.6.3
angular.module('workify').controller('TodoCtrl', function($scope) {
  chrome.storage.local.get('todolist', function(value) {
    return $scope.$apply(function() {
      return $scope.load(value);
    });
  });
  $scope.save = function() {
    return chrome.storage.local.set({
      todolist: $scope.todos
    });
  };
  $scope.load = function(value) {
    if (value && value.todolist.length > 0) {
      $scope.todos = value.todolist;
      return $scope.nextid = $scope.todos.length;
    } else {
      $scope.nextid = 0;
      $scope.todos = [];
      $scope.addTodo(["Build Workify", "Make workify save to chrome localstorage", "Make workify block pages", "Pass exams", "Learn WebGL"]);
      return $scope.save();
    }
  };
  $scope.addTodo = function(title) {
    if (title != null) {
      if (angular.isArray(title)) {
        $scope.todos.concat(_.map(function(el) {
          return _.extend(el, {
            done: false,
            id: $scope.nextid++
          });
        }));
      } else {
        $scope.todos.push({
          title: title,
          done: false,
          id: $scope.nextid++
        });
      }
      $scope.todoInput = "";
      return $scope.save();
    }
  };
});
