// Generated by CoffeeScript 1.6.3
"use strict";
angular.module('workify').controller('TodoCtrl', function($scope) {
  chrome.runtime.onMessage.addListener(function(msg) {
    if (msg === "updateList") {
      return chrome.storage.local.get('todolist', function(value) {
        return $scope.$apply(function() {
          return $scope.load(value);
        });
      });
    }
  });
  $scope.save = function() {
    chrome.storage.local.set({
      todolist: $scope.todos
    });
    return chrome.runtime.sendMessage("updateList");
  };
  $scope.save();
  $scope.load = function(value) {
    var _ref;
    if (value && ((_ref = value.todolist) != null ? _ref.length : void 0) > 0) {
      window.todos = _.clone(value.todolist);
      $scope.todos = value.todolist;
      return $scope.nextid = 1 + _.max($scope.todos, "id").id;
    }
  };
  $scope.addTodo = function(title, level) {
    console.log("title", title, "level", level);
    $scope.todos.push({
      title: title,
      done: false,
      id: $scope.nextid++,
      energy: level
    });
    $scope.todoInput = "";
    $scope.lowInput = "";
    $scope.highInput = "";
    return $scope.save();
  };
  $scope.clearComplete = function() {
    $scope.todos = _.where($scope.todos, {
      done: false
    });
    return $scope.save();
  };
  $scope.remove = function(id) {
    $scope.todos = _.reject($scope.todos, function(el) {
      return el.id === id;
    });
    return $scope.save();
  };
});
