// Generated by CoffeeScript 1.6.3
"use strict";
angular.module('workify').controller('TodoCtrl', function($scope) {
  chrome.runtime.onMessage.addListener(function(msg) {
    if (msg === "updateList") {
      return chrome.storage.local.get('todolist', function(value) {
        return $scope.$apply(function() {
          return $scope.load(value);
        });
      });
    }
  });
  $scope.save = function() {
    chrome.storage.local.set({
      todolist: $scope.todos
    });
    return chrome.runtime.sendMessage("updateList");
  };
  $scope.save();
  $scope.load = function(value) {
    var _ref;
    if (value && ((_ref = value.todolist) != null ? _ref.length : void 0) > 0) {
      $scope.todos = value.todolist;
      return $scope.nextid = $scope.todos.length;
    }
  };
  $scope.addTodo = function(_arg) {
    var level, title;
    title = _arg.title, level = _arg.level;
    console.log(title, level);
    $scope.todos.push({
      title: title,
      done: false,
      id: $scope.nextid++,
      energy: level
    });
    switch (level) {
      case "low":
        $scope.lowInput = "";
        break;
      case "high":
        $scope.highInput = "";
    }
    return $scope.save();
  };
  $scope.clearComplete = function() {
    $scope.todos = _.where($scope.todos, {
      done: false
    });
    return $scope.save();
  };
  $scope.remove = function(id) {
    return $scope.todos = _.reject($scope.todos, function(el) {
      return el.id === id;
    });
  };
});
